version: "3"

services:
  mongo:
    image: mongo:latest
  todo-api:
    ports:
      - "5000:5000"
    build: ./todo-api
  todo-ui:
    build: ./todo-ui
    ports:
      - "3500:3000"
    depends_on:
      - todo-api
